# Generated by Django 4.2.5 on 2023-10-04 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0006_userprofileinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='portfolio_site',
        ),
    ]
