# Generated by Django 4.2.5 on 2023-10-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0007_remove_userprofileinfo_portfolio_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
    ]
