# Generated by Django 4.2.5 on 2023-10-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0009_post_status_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
        migrations.DeleteModel(
            name='Draft',
        ),
    ]
