# Generated by Django 4.2.5 on 2023-10-12 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0013_readinghistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readinghistory',
            old_name='author',
            new_name='user',
        ),
    ]
