# Generated by Django 4.2.5 on 2023-10-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsite', '0014_rename_author_readinghistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='mode',
            field=models.CharField(choices=[('incognito', 'Incognito '), ('public', 'Public')], default='public', max_length=10),
        ),
    ]
